### ISSUE TITLE
[投稿] 我的 C 盘变大辣

### ISSUE THREAD

**Issue by Arispex** [JimmyRice/fuck-microsoft#1]
啊？3.8T？可是我电脑只有五百多个G...
<img width="798" alt="屏幕截图 2023-10-27 204723" src="https://github.com/JimmyRice/fuck-microsoft/assets/67822718/f6b4b622-3d49-4ea0-9eb8-e6bc20039bbd">
<img width="692" alt="屏幕截图 2023-10-27 204952" src="https://github.com/JimmyRice/fuck-microsoft/assets/67822718/04beb9c8-fb6d-4344-b1ac-89a4c31acfc0">

**Comment by JimmyRice** [comment]
Ok
